In [16]:
from math import factorial
from math import exp, pi, sqrt
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from scipy.stats import truncnorm
import scipy

from numpy import trapz

def combination(n, k):
    return int(factorial(n) / factorial(k) / factorial(n - k))

def arrangements(n, k):
    return int(factorial(n) / factorial(n - k))

1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):

zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].

Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.

Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [4]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [6]:
c = (zp*ks).mean()-zp.mean()*ks.mean()
c

9157.839999999997

In [10]:
np.cov(zp, ks)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [11]:
np.cov(zp, ks)[0, 1] #несмещеннная оценка

10175.377777777778

In [15]:
np.cov(zp, ks, ddof=0), np.cov(zp, ks, ddof=0)[0, 1] #смещенная оцена

(array([[ 3494.64,  9157.84],
        [ 9157.84, 30468.89]]), 9157.840000000002)

In [19]:
df = pd.DataFrame({'zp': zp, 'ks': ks}, columns=['zp', 'ks'])
df.head()

zp   ks
0   35  401
1   45  574
2  190  874
3  200  919
4   40  459

In [24]:
ne_cov = df.cov().values[0, 1] #несмещенная оценка
ne_cov

10175.377777777778

In [21]:
df.corr()

zp       ks
zp  1.00000  0.88749
ks  0.88749  1.00000

In [48]:
ks_n_std = ks.std(ddof=1) #несмещенная оценка стандартного отклонения (для небольших выборок)
ks_n_std

183.99544076477068

In [26]:
zp_n_std = zp.std(ddof=1)
zp_n_std

62.31318747531162

In [27]:
ne_cov/(ks_n_std*zp_n_std)

0.8874900920739162

In [28]:
c/(ks.std()*zp.std())

0.8874900920739158

2. Измерены значения IQ выборки студентов, обучающихся в местных технических вузах:

131, 125, 115, 122, 131, 115, 107, 99, 125, 111.

Известно, что в генеральной совокупности IQ распределен нормально.

Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [30]:
IQ = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
IQ

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [31]:
IQ.mean()

118.1

In [32]:
alphaover2 = 0.05/2
alphaover2

0.025

In [45]:
t = scipy.stats.t.ppf(1-0.025, len(IQ)-1) #Коэффициент Стьюдента
t

2.2621571627409915

In [49]:
IQ.mean()-(t*IQ.std(ddof=1))/((len(IQ)**0.5)) #нижняя граница с надежностью 0.95

110.55608365158724

In [47]:
IQ.mean()+(t*IQ.std(ddof=1))/((len(IQ)**0.5)) #верхняя граница с надежностью 0.95

125.64391634841274

3. Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

In [55]:
std = 25**(1/2) #сигма генеральной совокупности
n = 27
mu = 174.2
alphaover2 = 0.05/2
std, n, mu, alphaover2

(5.0, 27, 174.2, 0.025)

In [89]:
z_t = 1.96
z_t

1.96

In [91]:
mu-(z_t*std/(27**0.5)), mu+(z_t*std/(27**0.5))

(172.31398912064722, 176.08601087935276)