In [21]:
from math import factorial
from math import exp, pi, sqrt
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from scipy.stats import truncnorm
import scipy

from numpy import trapz

def combination(n, k):
    return int(factorial(n) / factorial(k) / factorial(n - k))

def arrangements(n, k):
    return int(factorial(n) / factorial(n - k))

1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [25]:
X = zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
X, y

(array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110]),
 array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832]))

In [24]:
n = len(X)
n

10

In [28]:
b = (np.mean(X*y)-np.mean(X)*np.mean(y))/(np.mean(X**2)-np.mean(X)**2)
a = np.mean(y)-b*np.mean(X)
a, b

(444.1773573243596, 2.620538882402765)

In [48]:
X = X.reshape(10,1)
y = y.reshape(10, 1)
X, y

(array([[ 35],
        [ 45],
        [190],
        [200],
        [ 40],
        [ 70],
        [ 54],
        [150],
        [120],
        [110]]), array([[401],
        [574],
        [874],
        [919],
        [459],
        [739],
        [653],
        [902],
        [746],
        [832]]))

In [49]:
B = np.dot(np.linalg.inv(np.dot(X.T, X)), X.T@y) #Без интерсепта
B

array([[5.88982042]])

In [51]:
X = np.hstack([np.ones((10, 1)), X])
X

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [53]:
B = np.dot(np.linalg.inv(np.dot(X.T, X)), X.T@y) #С интерсептом
B

array([[444.17735732],
       [  2.62053888]])

2. Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [54]:
X = zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
X, y

(array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110]),
 array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832]))

In [55]:
def mse_(B1, y=y , X=X, n=len(X)):
    return np.sum((B1*X-y)**2)/n

In [56]:
B1 = 0.1
alpha = 1e-6

In [63]:
for i in range(10000):
    B1 -= alpha*(2/n)*np.sum((B1*X-y)*X)
    if i%1000==0:
        print('iteration: {i}, B1={B1}, mse={mse}'.format(i=i, B1=B1, mse=mse_(B1)))

iteration: 0, B1=5.889820420132673, mse=56516.85841571943
iteration: 1000, B1=5.889820420132673, mse=56516.85841571943
iteration: 2000, B1=5.889820420132673, mse=56516.85841571943
iteration: 3000, B1=5.889820420132673, mse=56516.85841571943
iteration: 4000, B1=5.889820420132673, mse=56516.85841571943
iteration: 5000, B1=5.889820420132673, mse=56516.85841571943
iteration: 6000, B1=5.889820420132673, mse=56516.85841571943
iteration: 7000, B1=5.889820420132673, mse=56516.85841571943
iteration: 8000, B1=5.889820420132673, mse=56516.85841571943
iteration: 9000, B1=5.889820420132673, mse=56516.85841571943


3. Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (intercept).

In [64]:
X = zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
X, y

(array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110]),
 array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832]))

In [101]:
B0 = 0.1,
B1 = 0.1,
alpha = 0.05/1000

In [83]:
def mse_(B0, B1, y=y , X=X, n=len(X)):
    return np.sum((B0+B1*X-y)**2)/n

In [102]:
for i in range(1000000):
    y_pred = B0+B1*X
    B0 -= alpha*(2/n)*np.sum((y_pred-y))
    B1 -= alpha*(2/n)*np.sum((y_pred-y)*X)
    if i%25000==0:
        print('iteration: {i}, B0={B0}, B1={B1}, mse={mse}'.format(i=i, B0=B0, B1=B1, mse=mse_(B0, B1)))

iteration: 0, B0=[0.169966], B1=[8.07539], mse=122360.8044853729
iteration: 25000, B0=[208.67015558], B1=[4.35397601], mse=20539.593994170813
iteration: 50000, B0=[319.2658519], B1=[3.53994279], mse=10428.318419057196
iteration: 75000, B0=[377.92509807], B1=[3.1081848], mse=7583.841282812003
iteration: 100000, B0=[409.03758504], B1=[2.87918314], mse=6783.640544683958
iteration: 125000, B0=[425.53944806], B1=[2.75772213], mse=6558.530202561238
iteration: 150000, B0=[434.2919301], B1=[2.6933], mse=6495.202760188238
iteration: 175000, B0=[438.93419029], B1=[2.65913091], mse=6477.387652629451
iteration: 200000, B0=[441.39641525], B1=[2.64100785], mse=6472.375953981324
iteration: 225000, B0=[442.70236353], B1=[2.63139549], mse=6470.966076254969
iteration: 250000, B0=[443.3950301], B1=[2.62629716], mse=6470.569453205014
iteration: 275000, B0=[443.76241599], B1=[2.62359303], mse=6470.457876264116
iteration: 300000, B0=[443.95727511], B1=[2.62215878], mse=6470.426487736031
iteration: 325000, B